application:
  version: @application.version@
  title: @artifact.name@
  author: Vaganov V.S.

server:
  port : 8080

spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/testLehaim_db
    username : postgres
    password : admin

  jpa:
    generate-ddl : true
    hibernate :
      ddl-auto : validate
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  mvc:
    log-resolved-exception : false

  output:
    ansi:
      enabled : always

command-line-runner:
  data-loading:
    patients:
      enabled : true


logging:
  level:
    root: INFO
    ru.vaganov.lehaim.services: DEBUG
    ru.vaganov.lehaim.controllers: DEBUG

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

lehaim:
  report:
    radiation-therapy-days-before: 14
    radiation-therapy-days-after: 60
    operation-days-before: 14
    operation-days-after: 60
