name: Build

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  buildAndTest:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: build & test 
        run: mvn -B -f lehaim/pom.xml clean package
